name: utr-diffusion
channels:
  - nodefaults
  - pytorch
  - nvidia
  - conda-forge
  - bioconda

dependencies:
  - python=3.10
  - accelerate
  - matplotlib
  - numpy=1.26
  - pandas
  - pyyaml
  - pytest
  - scipy
  - scikit-learn
  - tqdm
  - einops
  - biopython
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - pip
  - logomaker
  - wandb
  - genomepy
  - bedtools
  - viennarna
  - pip:
      - memory-efficient-attention-pytorch
